# Generated by Django 5.1.2 on 2024-10-30 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_remove_staff_address_remove_staff_email_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomUser',
            new_name='Account',
        ),
    ]
