# Generated by Django 5.1.2 on 2024-10-30 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_customuser_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='role',
            field=models.CharField(choices=[('superadmin', 'Super Admin'), ('manager', 'Manager'), ('editor', 'Editor'), ('accountant', 'Accountant'), ('receptionist', 'Receptionist')], max_length=50),
        ),
    ]
