# Generated by Django 5.1.2 on 2025-01-03 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_parent_annual_income_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='division',
        ),
        migrations.RemoveField(
            model_name='student',
            name='standard',
        ),
    ]
