# Generated by Django 5.1.2 on 2025-01-03 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_parent_occupation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parent',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=20, verbose_name='WhatsApp number'),
        ),
    ]
