# Generated by Django 5.1.2 on 2024-10-30 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_student_standard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='standard',
            field=models.IntegerField(null=True),
        ),
    ]
