# Generated by Django 5.1.2 on 2024-12-10 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_account_address_alter_account_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='standard',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
