# Generated by Django 5.1.2 on 2024-12-15 20:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('standard', models.CharField(max_length=50)),
                ('class_teacher', models.ForeignKey(limit_choices_to={'groups__name': 'Teacher'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classrooms_leading', to=settings.AUTH_USER_MODEL)),
                ('other_teachers', models.ManyToManyField(blank=True, limit_choices_to={'groups__name': 'Teacher'}, related_name='classrooms_assisting', to=settings.AUTH_USER_MODEL)),
                ('students', models.ManyToManyField(blank=True, limit_choices_to={'groups__name': 'Student'}, related_name='classrooms', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField()),
                ('additional_students', models.ManyToManyField(blank=True, limit_choices_to={'groups__name': 'Student'}, related_name='subjects', to=settings.AUTH_USER_MODEL)),
                ('classroom', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subjects', to='allocation.classroom')),
                ('main_teacher', models.ForeignKey(limit_choices_to={'groups__name': 'Teacher'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subjects_leading', to=settings.AUTH_USER_MODEL)),
                ('other_teachers', models.ManyToManyField(blank=True, limit_choices_to={'groups__name': 'Teacher'}, related_name='subjects_assisting', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
