# Generated by Django 5.1.4 on 2025-01-05 09:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("allocation", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="classroom",
            name="class_teacher",
            field=models.ForeignKey(
                limit_choices_to={"groups__name": "Teacher"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="classrooms_leading",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="classroom",
            name="other_teachers",
            field=models.ManyToManyField(
                blank=True,
                limit_choices_to={"groups__name": "Teacher"},
                related_name="classrooms_assisting",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="classroom",
            name="students",
            field=models.ManyToManyField(
                blank=True,
                limit_choices_to={"groups__name": "Student"},
                related_name="classrooms",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="classroomjoinlinks",
            name="classroom",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="join_links",
                to="allocation.classroom",
            ),
        ),
        migrations.AddField(
            model_name="classroomjoinlinks",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="classroom_join_links",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="subject",
            name="additional_students",
            field=models.ManyToManyField(
                blank=True,
                limit_choices_to={"groups__name": "Student"},
                related_name="subjects",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="subject",
            name="classroom",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="subjects",
                to="allocation.classroom",
            ),
        ),
        migrations.AddField(
            model_name="subject",
            name="main_teacher",
            field=models.ForeignKey(
                limit_choices_to={"groups__name": "Teacher"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="subjects_leading",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="subject",
            name="other_teachers",
            field=models.ManyToManyField(
                blank=True,
                limit_choices_to={"groups__name": "Teacher"},
                related_name="subjects_assisting",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
