# Generated by Django 5.1.2 on 2024-12-10 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_account_address_alter_account_first_name_and_more'),
        ('allocation', '0003_alter_classroom_class_teacher_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='other_teachers',
            field=models.ManyToManyField(limit_choices_to={'group': 'Teacher'}, related_name='classrooms_assisting', to='accounts.account'),
        ),
    ]
