# Generated by Django 5.1.2 on 2024-12-10 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_account_standard'),
        ('allocation', '0004_alter_classroom_other_teachers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='class_teacher',
            field=models.ForeignKey(limit_choices_to={'groups__name': 'Teacher'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classrooms_leading', to='accounts.account'),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='other_teachers',
            field=models.ManyToManyField(limit_choices_to={'groups__name': 'Teacher'}, related_name='classrooms_assisting', to='accounts.account'),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='students',
            field=models.ManyToManyField(limit_choices_to={'groups__name': 'Student'}, related_name='classrooms', to='accounts.account'),
        ),
    ]
