# Generated by Django 5.1.2 on 2024-12-11 06:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_account_standard'),
        ('allocation', '0005_alter_classroom_class_teacher_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='additional_students',
            field=models.ManyToManyField(limit_choices_to={'groups__name': 'Student'}, related_name='subjects', to='accounts.account'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='main_teacher',
            field=models.ForeignKey(limit_choices_to={'groups__name': 'Teacher'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subjects_leading', to='accounts.account'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='other_teachers',
            field=models.ManyToManyField(limit_choices_to={'groups__name': 'Teacher'}, related_name='subjects_assisting', to='accounts.account'),
        ),
    ]
