# Generated by Django 5.1.2 on 2024-12-11 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_account_standard'),
        ('allocation', '0006_alter_subject_additional_students_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='other_teachers',
            field=models.ManyToManyField(blank=True, limit_choices_to={'groups__name': 'Teacher'}, related_name='classrooms_assisting', to='accounts.account'),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='students',
            field=models.ManyToManyField(blank=True, limit_choices_to={'groups__name': 'Student'}, related_name='classrooms', to='accounts.account'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='additional_students',
            field=models.ManyToManyField(blank=True, limit_choices_to={'groups__name': 'Student'}, related_name='subjects', to='accounts.account'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='other_teachers',
            field=models.ManyToManyField(blank=True, limit_choices_to={'groups__name': 'Teacher'}, related_name='subjects_assisting', to='accounts.account'),
        ),
    ]
