# Generated by Django 5.1.2 on 2024-12-19 07:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("allocation", "0001_initial"),
        ("assignments", "0002_assignment_classroom_submittedassignment_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assignment",
            name="classroom",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="classrooms",
                to="allocation.classroom",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="assignment",
            name="subject",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assignments",
                to="allocation.subject",
            ),
            preserve_default=False,
        ),
    ]
