# Generated by Django 5.1.2 on 2024-12-20 06:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assignments", "0003_alter_assignment_classroom_alter_assignment_subject"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="submittedassignment",
            name="assignment",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assignment",
                to="assignments.assignment",
            ),
        ),
        migrations.AlterField(
            model_name="submittedassignment",
            name="student",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="student",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="submittedassignment",
            name="submission_datetime",
            field=models.DateTimeField(blank=True),
        ),
    ]
