# Generated by Django 5.1.2 on 2024-10-29 05:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('allocation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('release_date', models.DateTimeField()),
                ('expiry_date', models.DateTimeField()),
                ('classrooms', models.ManyToManyField(blank=True, related_name='attachments', to='allocation.classroom')),
                ('signed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.teacher')),
                ('subjects', models.ManyToManyField(blank=True, related_name='attachments', to='allocation.subject')),
            ],
        ),
    ]
