# Generated by Django 5.1.2 on 2024-12-15 22:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0001_initial'),
        ('attachments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='announcement',
            old_name='expiry_date',
            new_name='expiry_datetime',
        ),
        migrations.RenameField(
            model_name='announcement',
            old_name='release_date',
            new_name='release_datetime',
        ),
        migrations.AddField(
            model_name='announcement',
            name='attachments',
            field=models.ManyToManyField(blank=True, related_name='announcements', to='attachments.attachment'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='announcements_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='signed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='announcements_signed', to=settings.AUTH_USER_MODEL),
        ),
    ]
