# Generated by Django 5.1.2 on 2024-12-16 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0002_rename_expiry_date_announcement_expiry_datetime_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='announcement',
            old_name='expiry_datetime',
            new_name='expiry_at',
        ),
        migrations.RenameField(
            model_name='announcement',
            old_name='release_datetime',
            new_name='release_at',
        ),
    ]
