# Generated by Django 5.1.2 on 2024-12-10 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allocation', '0003_alter_classroom_class_teacher_and_more'),
        ('announcements', '0002_alter_announcement_signed_by'),
        ('attachments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='attachments',
            field=models.ManyToManyField(blank=True, related_name='announcements', to='attachments.attachment'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='priority',
            field=models.CharField(blank=True, choices=[('low', 'Low Priority'), ('medium', 'Medium Priority'), ('high', 'High  Priority')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='classrooms',
            field=models.ManyToManyField(blank=True, related_name='announcements', to='allocation.classroom'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='subjects',
            field=models.ManyToManyField(blank=True, related_name='announcements', to='allocation.subject'),
        ),
    ]
