# Generated by Django 5.1.2 on 2024-12-10 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0003_announcement_attachments_announcement_priority_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='attachments',
        ),
    ]
