# Generated by Django 5.1.2 on 2025-01-01 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attachments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='additional_info',
            field=models.TextField(blank=True, null=True),
        ),
    ]
