# Generated by Django 5.1.2 on 2024-12-10 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attachments', '0002_attachment_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attachment',
            old_name='Name',
            new_name='name',
        ),
    ]
