# Generated by Django 5.1.2 on 2025-01-01 00:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attachments', '0002_attachment_additional_info'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Phone number')),
                ('whatsapp', models.CharField(blank=True, max_length=20, verbose_name='WhatsApp number')),
                ('occupation', models.CharField(blank=True, max_length=400, verbose_name='Occupation')),
                ('office_address', models.TextField(blank=True, null=True)),
                ('annual_income', models.CharField(blank=True, max_length=50, verbose_name='Annual Income')),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parent_account', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_no', models.CharField(max_length=50, unique=True)),
                ('roll_no', models.CharField(blank=True, max_length=50, null=True)),
                ('standard', models.CharField(blank=True, max_length=50, null=True)),
                ('division', models.CharField(blank=True, max_length=10, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('aadhar_card_no', models.CharField(blank=True, max_length=50, null=True)),
                ('previous_school_student_id', models.CharField(blank=True, max_length=50, null=True)),
                ('religion', models.CharField(blank=True, max_length=100, null=True)),
                ('birth_place', models.CharField(blank=True, max_length=100, null=True)),
                ('mother_tongue', models.CharField(blank=True, max_length=50, null=True)),
                ('nationality', models.CharField(blank=True, max_length=50, null=True)),
                ('caste', models.CharField(blank=True, max_length=100, null=True)),
                ('medical_info', models.TextField(blank=True, null=True)),
                ('prev_school_name', models.CharField(blank=True, max_length=255, null=True)),
                ('prev_school_address', models.TextField(blank=True, null=True)),
                ('prev_school_udise_no', models.CharField(blank=True, max_length=100, null=True)),
                ('prev_school_board', models.CharField(blank=True, max_length=100, null=True)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_account', to=settings.AUTH_USER_MODEL)),
                ('address_proof', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_address_proof', to='attachments.attachment')),
                ('birth_certificate', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_birth_certificate', to='attachments.attachment')),
                ('character_certificate', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_character_certificate', to='attachments.attachment')),
                ('guardian_1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_guardian1', to='users.parent')),
                ('guardian_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_guardian2', to='users.parent')),
                ('id_card', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_id_card', to='attachments.attachment')),
                ('identity_proof', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_identity_proof', to='attachments.attachment')),
                ('leaving_certificate', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_leaving_certificate', to='attachments.attachment')),
                ('report_cards', models.ManyToManyField(blank=True, related_name='student_report_cards', to='attachments.attachment')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.BigIntegerField(verbose_name='ID')),
                ('qualifications', models.TextField(blank=True, verbose_name='Qualifications')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Phone number')),
                ('whatsapp', models.CharField(blank=True, max_length=20, verbose_name='WhatsApp number')),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_account', to=settings.AUTH_USER_MODEL)),
                ('docs', models.ManyToManyField(null=True, related_name='teacher_docs', to='attachments.attachment')),
            ],
        ),
    ]
