# Generated by Django 5.1.2 on 2025-01-01 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attachments', '0002_attachment_additional_info'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='docs',
            field=models.ManyToManyField(related_name='teacher_docs', to='attachments.attachment'),
        ),
    ]
