# Generated by Django 5.1.2 on 2025-01-01 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_teacher_docs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='address_proof',
        ),
        migrations.RemoveField(
            model_name='student',
            name='birth_certificate',
        ),
        migrations.RemoveField(
            model_name='student',
            name='character_certificate',
        ),
        migrations.RemoveField(
            model_name='student',
            name='id_card',
        ),
        migrations.RemoveField(
            model_name='student',
            name='identity_proof',
        ),
        migrations.RemoveField(
            model_name='student',
            name='leaving_certificate',
        ),
        migrations.RemoveField(
            model_name='student',
            name='prev_school_address',
        ),
        migrations.RemoveField(
            model_name='student',
            name='prev_school_board',
        ),
        migrations.RemoveField(
            model_name='student',
            name='prev_school_name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='prev_school_udise_no',
        ),
        migrations.RemoveField(
            model_name='student',
            name='previous_school_student_id',
        ),
        migrations.RemoveField(
            model_name='student',
            name='report_cards',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='docs',
        ),
    ]
