name: Node

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
env: 
  CI: false
  
jobs:
  release:
    permissions: write-all
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: ./frontend/build.sh
    - name: Set tag name
      id: tag
      run: |
        if [[ "${{ github.event_name }}" != "push" ]]; then
          tag=v$(date +%Y%m%d.%H%M%S)
        else
          tag=$(echo $GITHUB_SHA | cut --characters=-10)
        fi
        echo "tag=$tag" >> $GITHUB_OUTPUT
    - name: Publish Release Build
      id: create_release
      uses: actions/create-release@v1
      env: 
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        prerelease: false
        draft: true
        tag_name: ${{ steps.tag.outputs.tag }}
        release_name: release
    - uses: actions/upload-release-asset@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./frontend/build.tar.xz
        asset_name: build.tar.xz
        asset_content_type: application/tar+gzip

    - uses: eregon/publish-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        release_id: ${{ steps.create_release.outputs.id }}
